function centroid_FourierDescriptor=im2centroid_FourierDescriptor(im)

b = bwboundaries(im);
boundary = b{1};
np=length(boundary);
s=sum(boundary,1);
x=s(1,2)./np;
y=s(1,1)./np;
d=sqrt((boundary(:,2)-x).^2+(boundary(:,1)-y).^2);
x=1:np;
y=d;
N=300;
xi=linspace(1,np,N);
yi=spline(x,y,xi);
% xii=(0:N-1);
yii=yi;
fd=fft(yii,N);
fd(1)=0;
fd=fd./abs(fd(2));
v=fd(2:101);
v=v';
data=[real(v);imag(v)];
centroid_FourierDescriptor=data;